// third-party
import { FormattedMessage } from "react-intl";
import { NavItemType } from "types";

// assets
import {
  IconApps,
  IconUserCheck,
  IconBasket,
  IconFileInvoice,
  IconMessages,
  IconLayoutKanban,
  IconHome,
  IconMail,
  IconCalendar,
  IconNfc,
  IconInfoCircle,
  IconTool,
  IconBook,
  IconMovie,
  IconArticle,
  IconAward,
  IconPhonePlus,
  IconMessageQuestion,
  IconClipboardList,
  IconMapPin,
  IconBrandTabler,
  IconBrandRumble,
  IconSettings,
  IconUser,
  IconUserQuestion,
  IconBellRinging,
  IconCalendarCheck,
  IconStairsUp,
  IconUserPlus,
  IconAddressBook,
  IconPencil,
  IconUserDown,
  IconFileDescription,
  IconBell,
  IconStar,
  IconLocation,
  IconUsersGroup,
  IconHelpHexagon,
  IconAdjustmentsCog,
  IconHomeDollar,
  IconCashBanknote,
  IconPhotoPlus,
  IconBasketCog,
  IconEye,
} from "@tabler/icons-react";

// constant
const icons = {
  IconApps,
  IconUserCheck,
  IconBasket,
  IconFileInvoice,
  IconMessages,
  IconLayoutKanban,
  IconMail,
  IconCalendar,
  IconNfc,
  IconInfoCircle,
  IconTool,
  IconHome,
  IconBook,
  IconMovie,
  IconArticle,
  IconAward,
  IconPhonePlus,
  IconMessageQuestion,
  IconClipboardList,
  IconMapPin,
  IconBrandTabler,
  IconBrandRumble,
  IconSettings,
  IconUser,
  IconUserQuestion,
  IconBellRinging,
  IconCalendarCheck,
  IconStairsUp,
  IconUserPlus,
  IconAddressBook,
  IconPencil,
  IconUserDown,
  IconFileDescription,
  IconBell,
  IconStar,
  IconLocation,
  IconUsersGroup,
  IconHelpHexagon,
  IconAdjustmentsCog,
  IconHomeDollar,
  IconCashBanknote,
  IconPhotoPlus,
  IconBasketCog,
  IconEye,
};

// ==============================|| MENU ITEMS - APPLICATION ||============================== //

const application: NavItemType = {
  id: "application",
  title: <FormattedMessage id="application" />,
  icon: icons.IconApps,
  type: "group",
  children: [
    {
      id: "users-list",
      title: <FormattedMessage id="users-list" />,
      type: "item",
      url: "/user",
      icon: icons.IconUser,
    },
    {
      id: "home-list",
      title: <FormattedMessage id="home-list" />,
      type: "item",
      url: "/home",
      icon: icons.IconHome,
    },
    {
      id: "about-us",
      title: <FormattedMessage id="about-us" />,
      type: "item",
      url: "/about-us",
      icon: icons.IconInfoCircle,
    },
    {
      id: "service",
      title: <FormattedMessage id="service" />,
      type: "collapse",
      icon: icons.IconHelpHexagon,
      children: [
        {
          id: "service-list",
          title: <FormattedMessage id="service-list" />,
          type: "item",
          url: "/service",
        },
        {
          id: "service-carousel-images",
          title: <FormattedMessage id="service-carousel-images" />,
          type: "item",
          url: "/service-carousel",
        },
        // {
        //   id: "service-images",
        //   title: <FormattedMessage id="service-images" />,
        //   type: "item",
        //   url: "/service-image",
        // },

        {
          id: "service-section",
          title: <FormattedMessage id="service-section" />,
          type: "item",
          url: "/service-section",
        },
        {
          id: "why-choose-us-header",
          title: <FormattedMessage id="why-choose-us-header" />,
          type: "item",
          url: "/why-choose-us-header",
        },
        {
          id: "why-choose-us",
          title: <FormattedMessage id="why-choose-us" />,
          type: "item",
          url: "/why-choose-us",
        },
      ],
    },
    {
      id: "projects",
      title: <FormattedMessage id="projects" />,
      type: "collapse",
      icon: icons.IconBasketCog,
      children: [
        {
          id: "projects-list",
          title: <FormattedMessage id="projects-list" />,
          type: "item",
          url: "/project",
        },
        {
          id: "projects-main-image",
          title: <FormattedMessage id="projects-main-image" />,
          type: "item",
          url: "/project-main-image",
        },
        {
          id: "projects-images",
          title: <FormattedMessage id="projects-images" />,
          type: "item",
          url: "/project-image",
        },
      ],
    },

    {
      id: "design-build",
      title: <FormattedMessage id="design-build" />,
      type: "collapse",
      icon: icons.IconFileDescription,
      children: [
        {
          id: "design-build",
          title: <FormattedMessage id="design-build" />,
          type: "item",
          url: "/design-build",
        },
        {
          id: "design-construction",
          title: <FormattedMessage id="design-construction" />,
          type: "item",
          url: "/design-and-construction",
        },
        {
          id: "design-gallery",
          title: <FormattedMessage id="design-gallery" />,
          type: "item",
          url: "/design-gallery",
        },
        {
          id: "our-design-header",
          title: <FormattedMessage id="our-design-header" />,
          type: "item",
          url: "/build-journey-header",
        },
        {
          id: "our-design",
          title: <FormattedMessage id="our-design" />,
          type: "item",
          url: "/build-journey",
        },
        {
          id: "our-design-images",
          title: <FormattedMessage id="our-design-images" />,
          type: "item",
          url: "/build-image",
        },
      ],
    },

    {
      id: "blogs-list",
      title: <FormattedMessage id="blogs-list" />,
      type: "item",
      icon: icons.IconPencil,
      url: "/blog",
    },

    // {
    //   id: "consultation-booking",
    //   title: <FormattedMessage id="consultation-booking" />,
    //   type: "item",
    //   url: "/consultation-booking",
    //   icon: icons.IconBook,
    // },
    // {
    //   id: 'testimonial',
    //   title: <FormattedMessage id="testimonial" />,
    //   type: 'item',
    //   url: '/testimonial',
    //   icon: icons.IconMessageQuestion,
    // },
    // {
    //   id: 'our-team',
    //   title: <FormattedMessage id="our-team" />,
    //   type: 'item',
    //   icon: icons.IconUsersGroup,
    //   url: '/team',
    // },
    // {
    //   id: 'why-choose-us',
    //   title: <FormattedMessage id="why-choose-us" />,
    //   type: 'collapse',
    //   icon: icons.IconHelpHexagon,
    //   children: [
    //     {
    //       id: 'why-choose-us',
    //       title: <FormattedMessage id="why-choose-us-list" />,
    //       type: 'item',
    //       url: '/why-choose-us',
    //     },
    //     {
    //       id: 'why-choose-us-details',
    //       title: <FormattedMessage id="why-choose-us-detail" />,
    //       type: 'item',
    //       url: '/why-choose-us-detail',
    //     },
    //   ],
    // },
    {
      id: "how-we-work",
      title: <FormattedMessage id="how-we-work" />,
      type: "item",
      icon: icons.IconAdjustmentsCog,
      url: "/how-we-work",
    },
    {
      id: "faq-list",
      title: <FormattedMessage id="faq-list" />,
      type: "item",
      url: "/faq",
      icon: icons.IconUserQuestion,
    },
    {
      id: "contact-us-list",
      title: <FormattedMessage id="contact-us-list" />,
      type: "item",
      url: "/contact-us",
      icon: icons.IconAddressBook,
    },
    {
      id: "setting",
      title: <FormattedMessage id="setting" />,
      type: "collapse",
      icon: icons.IconSettings,
      children: [
        // {
        //   id: "subscriptions",
        //   title: <FormattedMessage id="subscriptions" />,
        //   type: "item",
        //   url: "/subscription",
        //   // icon: icons.IconBell,
        // },
        {
          id: "breadcrumb-list",
          title: <FormattedMessage id="breadcrumb-list" />,
          type: "item",
          url: "/breadcrumb",
          // icon: icons.IconBrandRumble,
        },

        {
          id: "static-seo",
          title: <FormattedMessage id="static-seo" />,
          type: "item",
          url: "/seo",
        },
        {
          id: "privacy-list",
          title: <FormattedMessage id="privacy-list" />,
          type: "item",
          url: "/privacy",
          // icon: icons.IconFileDescription,
        },
        {
          id: "terms-list",
          title: <FormattedMessage id="terms-list" />,
          type: "item",
          url: "/term",
          // icon: icons.IconFileDescription,
        },
        {
          id: "organization-settings",
          title: <FormattedMessage id="organization-settings" />,
          type: "item",
          url: "/setting",
          // icon: icons.IconSettings,
        },
      ],
    },
  ],
};

export default application;
